### ISSUE TITLE
Is ruby the best option?

### ISSUE THREAD

**Issue by maxguzenski** [stravid/mountable_file_server#2]
Hi, I read you blog post and I already tested refile and dragonfly in the pass (but not in production). 

I have a website with 2millions of pageview / day, and user upload more o less 5k photos/day and I cant use cloud image solutions like imgx and clodinary because it is a porn website ;)... 

This website run on Ruby on Rails. and I'm long time searching for an open source solution or think the best one to implement one by myself but I haven't sure if ruby is the best fit to make this. Its look like to be a very good use case for golang, or even nodejs... but last one to ruby, even with use of CDN/nginx/varnish.  

My question is: why you choose ruby? is there any especial reason that I can see?

thanks a lot

**Comment by RKushnir** [comment]
@maxguzenski I recommend you to take a look at thumbor, written in Python, secure, feature-rich and extensible(you can write your own image filters). I'm using it for a few months and haven't had issues with it.

**Comment by stravid** [comment]
Hi @maxguzenski I'm surprised it's against the policy to host pornographic content with imgx and Co. But well it's none of my business.

Regarding your main question why I picked Ruby: I know Ruby the best and need something I can use within other Ruby applications. I certainly did not pick Ruby for performance reasons.

Speaking of performance there are a few key points to consider. Do you have problems with storing 5K photos per day or generating the processed images for the 2M+ page views per day?

Once generated the modified photos should be served by something appropriate like nginx, Varnish or a CDN and not your processing endpoint. To speed up processing you should look for solutions that build upon high performance libraries like libvips. Separating the upload and process endpoints will also allow you to pick the best tool for the job.

@RKushnir Thanks for pointing out the obvious. An unfinished gem is years behind an established library that's existing for years. What a surprise.

Next time consider writing something along the lines of

> I'm not answering your question but can recommend thumbor, a feature-rich Python alternative.

instead of being a dick.

**Comment by RKushnir** [comment]
@stravid Sorry for hurting your feelings as a developer and inventor. I didn't intend being a dick.
I assume the OP is looking for a solid solution to use in his real business application. So, yes, it's nice, interesting and educating to re-invent your own bicycle, but it's very irresponsible to suggest it's a thing other people can use in production. And I wasn't pointing out the obvious, — without looking at the commit history it's hard to tell if it's a result of a one night hack or a product of years of development. You said it's an `unfinished gem`, and there's better alternatives, now we made it clear — that was my intention.

**Comment by stravid** [comment]
@RKushnir Sorry for calling you a dick. I assumed the worst and got hurt when I shouldn't have. Sorry again.

Do you know of any Ruby based processing libraries like thumbor? Since I have zero experience with Python I would consider it careless to use it in production for my applications and not know a thing about Python deployments.

After this weekends refactor I'm also pretty sure it's best to see uploading and processing as two separate things. Processing images should not be part of an file upload library.

**Comment by RKushnir** [comment]
No worries.
Actually, thumbor is a service that you can treat as a blackbox. Just set it up as you would with nginx or elasticsearch. nginx is written in C, elasticsearch in Java, and thumbor in Python, they may have different installation procedures, but after that you don't care, cause you just have to run an executable file.

You may find this guide interesting, I used it for my setup with Amazon S3: http://www.dadoune.com/blog/best-thumbnailing-solution-set-up-thumbor-on-aws/

**Comment by stravid** [comment]
@maxguzenski Is your question sufficiently answered?

**Comment by maxguzenski** [comment]
Hi, yes. Thanks a lot ;)
